### PR TITLE
added port binding

### PR DESCRIPTION
**Pull request by cron410**

### CODE REVIEW

**Comment by qdm12** [comment]
Hi @cron410 

Thanks for your pull request ! I however believe there is no need for the TCP port but only for the UDP port. Why do you want to add the TCP port (28960)?

**Comment by cron410** [comment]
It's just cleaner because the server binds to both. I'm not quite sure but
cod4x master server might use TCP for something. My server stopped showing
in the game server list when I removed TCP forwarding in the router. I'll
have to check tomorrow to see if it shows up.

**Comment by qdm12** [comment]
Hello! Sorry I completely forgot your PRs for like 2 years!! My apologies...

Anyway, I just applied your fixes as #8 needed the masterlist to work. It seems to work with the UDP port only but let's play it safe with the TCP port too.

Thanks again!

**Comment by cron410** [comment]
No worries, I'm pretty bad at following up with Github stuff as well.

**Pull request closed without merging**
